export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN_SUCCESS";
export const IS_LOGGED_IN_FAILURE = "IS_LOGGED_IN_FAILURE";

export const CONFIRMATION_CODE = "CONFIRMATION_CODE";
export const CONFIRMATION_CODE_SUCCESS = "CONFIRMATION_CODE_SUCCESS";
export const CONFIRMATION_CODE_FAILURE = "CONFIRMATION_CODE_FAILURE";

export const CONFIRM_NEW_PASSWORD = "CONFIRM_NEW_PASSWORD";
export const CONFIRM_NEW_PASSWORD_SUCCESS = "CONFIRM_NEW_PASSWORD_SUCCESS";
export const CONFIRM_NEW_PASSWORD_FAILURE = "CONFIRM_NEW_PASSWORD_FAILURE";